dspace:
  build: .
  links:
    - db
    - solr
  ports:
    - "80:80"
  volumes:
        - /opt/solr/server/solr/dspace
        - /var/www

db:
  image: mysql
  volumes:
    - /var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_USER: admin
    MYSQL_PASSWORD: admin
    MYSQL_DATABASE: dspace

solr:
  image: solr:5 #drupal v7 only currently support v5
  command: [solr-precreate, dspace]


