drupal:
  build: drupal 
  links:
    - db
    - solr
  ports:
    - "80:80"
  volumes_from:
    - www-data

db:
  image: mysql
  volumes:
    - /var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_USER: admin
    MYSQL_PASSWORD: admin
    MYSQL_DATABASE: dspace

solr:
  image: solr:5 #drupal v7 only currently support v5
  command: [solr-precreate, gpii-dspace, /var/www/solr]
  volumes_from:
    - www-data
  
www-data:
  build: . 
  volumes:
    - /var/www
