drupal:
  build: drupal 
  links:
    - db
    - solr
#    - vdebug
  ports:
    - "80:80"
  volumes_from:
    - www-data
#  environment:
#    XDEBUG_CONFIG: idekey=docdrupal remote_host=vdebug profiler_enable=1

db:
  image: mysql
  volumes:
    - /var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_USER: admin
    MYSQL_PASSWORD: admin
    MYSQL_DATABASE: dspace

solr:
  image: solr:5 #drupal v7 only currently support v5
  command: [solr-precreate, gpii-dspace, /var/www/solr]
  volumes_from:
    - www-data


#vdebug:
#  build: vdebug 
#  volumes_from:
#    - www-data
#  command: -c VdebugStart
#  working_dir: /var/www/html

www-data:
  build: . 
  volumes:
    - /var/www
